services:
  brainrot:
    build:
      context: ./pwn/brainrot/service
    container_name: brainrot
    ports:
      - "31337:30000"
    networks:
      - net0
    read_only: true
    deploy:
      resources:
        limits:
          memory: 128M
          pids: 256
      restart_policy:
        condition: always
        delay: 3s
    cap_drop:
      - ALL

networks:
  net0:
