//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// ------------------- Function Prototypes --------------------

int64_t __do_global_dtors_aux(void);
int64_t _fini(void);
int64_t _init(void);
int64_t _start(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6);
int64_t a(int64_t * str);
int64_t b(int64_t * str);
int64_t c(int64_t * str, int64_t a2);
int64_t d(int64_t * str, int64_t a2);
int64_t deregister_tm_clones(void);
int64_t e(int64_t * str);
int64_t f(int64_t * str);
int64_t frame_dummy(void);
int32_t function_1030(int32_t c2);
int32_t function_1040(char * s);
int32_t function_1050(char * format, ...);
void function_1060(int64_t * d2);
int64_t register_tm_clones(void);

// --------------------- Global Variables ---------------------

int64_t g1 = 0; // 0x3fe0
int64_t g2 = 0; // 0x4028
int32_t g3;

// ------- Dynamically Linked Functions Without Header --------

void __cxa_finalize(int64_t * a1);
void __gmon_start__(void);
int32_t __libc_start_main(int64_t a1, int32_t a2, char ** a3, void (*a4)(), void (*a5)(), void (*a6)());

// ------------------------ Functions -------------------------

// Address range: 0x1000 - 0x1017
int64_t _init(void) {
    int64_t result = 0; // 0x100e
    if (*(int64_t *)0x3fd0 != 0) {
        // 0x1010
        __gmon_start__();
        result = &g3;
    }
    // 0x1012
    return result;
}

// Address range: 0x1030 - 0x1036
int32_t function_1030(int32_t c2) {
    // 0x1030
    return putchar(c2);
}

// Address range: 0x1040 - 0x1046
int32_t function_1040(char * s) {
    // 0x1040
    return strlen(s);
}

// Address range: 0x1050 - 0x1056
int32_t function_1050(char * format, ...) {
    // 0x1050
    return printf(format);
}

// Address range: 0x1060 - 0x1066
void function_1060(int64_t * d2) {
    // 0x1060
    __cxa_finalize(d2);
}

// Address range: 0x1070 - 0x1092
int64_t _start(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6) {
    // 0x1070
    int64_t v1; // 0x1070
    __libc_start_main(0x1159, (int32_t)a6, (char **)&v1, NULL, NULL, (void (*)())a3);
    __asm_hlt();
    // UNREACHABLE
}

// Address range: 0x10a0 - 0x10c9
int64_t deregister_tm_clones(void) {
    // 0x10a0
    return &g2;
}

// Address range: 0x10d0 - 0x1109
int64_t register_tm_clones(void) {
    // 0x10d0
    return 0;
}

// Address range: 0x1110 - 0x1149
int64_t __do_global_dtors_aux(void) {
    // 0x1110
    if (*(char *)&g2 != 0) {
        // 0x1148
        int64_t result; // 0x1110
        return result;
    }
    // 0x111d
    if (g1 != 0) {
        // 0x112b
        __cxa_finalize((int64_t *)*(int64_t *)0x4020);
    }
    int64_t result2 = deregister_tm_clones(); // 0x1137
    *(char *)&g2 = 1;
    return result2;
}

// Address range: 0x1150 - 0x1159
int64_t frame_dummy(void) {
    // 0x1150
    return register_tm_clones();
}

// Address range: 0x1159 - 0x11ff
int main(int argc, char ** argv) {
    int64_t v1 = 0x696c427265627943; // bp-40, 0x1175
    a(&v1);
    b(&v1);
    c(&v1, 90);
    d(&v1, 3);
    e(&v1);
    f(&v1);
    printf("Output: %s\n", &v1);
    return 0;
}

// Address range: 0x11ff - 0x125c
// Demangled:     signed char
int64_t a(int64_t * str) {
    // 0x11ff
    if (strlen((char *)str) == 0) {
        // 0x1254
        return 0;
    }
    int32_t v1 = 0; // 0x1252
    char * v2 = (char *)((int64_t)v1 + (int64_t)str); // 0x1222
    *v2 = *v2 + 1;
    v1++;
    int32_t len = strlen((char *)str); // 0x124a
    while (v1 < len) {
        // 0x1215
        v2 = (char *)((int64_t)v1 + (int64_t)str);
        *v2 = *v2 + 1;
        v1++;
        len = strlen((char *)str);
    }
    // 0x1254
    return len;
}

// Address range: 0x125c - 0x12e0
// Demangled:     bool
int64_t b(int64_t * str) {
    uint32_t v1 = strlen((char *)str) - 1; // 0x127b
    if (v1 <= 0) {
        // 0x12dc
        return 0;
    }
    int64_t v2 = (int64_t)str;
    int64_t result = v1;
    int64_t v3 = 0;
    char * v4 = (char *)(v3 + v2); // 0x1290
    char v5 = *v4; // 0x1290
    char * v6 = (char *)((int64_t)v5 + v2); // 0x12af
    *v4 = *v6;
    *v6 = v5;
    v3++;
    while (v3 != result) {
        // 0x1283
        v4 = (char *)(v3 + v2);
        v5 = *v4;
        v6 = (char *)((int64_t)v5 + v2);
        *v4 = *v6;
        *v6 = v5;
        v3++;
    }
    // 0x12dc
    return result;
}

// Address range: 0x12e0 - 0x1340
// Demangled:     char
int64_t c(int64_t * str, int64_t a2) {
    // 0x12e0
    if (strlen((char *)str) == 0) {
        // 0x1338
        return 0;
    }
    int32_t v1 = 0; // 0x131d
    char * v2 = (char *)((int64_t)v1 + (int64_t)str); // 0x1308
    *v2 = *v2 ^ (char)a2;
    v1++;
    int32_t len = strlen((char *)str); // 0x132e
    while (v1 < len) {
        // 0x12fb
        v2 = (char *)((int64_t)v1 + (int64_t)str);
        *v2 = *v2 ^ (char)a2;
        v1++;
        len = strlen((char *)str);
    }
    // 0x1338
    return len;
}

// Address range: 0x1340 - 0x13c5
// Demangled:     double
int64_t d(int64_t * str, int64_t a2) {
    // 0x1340
    if (strlen((char *)str) == 0) {
        // 0x13bd
        return 0;
    }
    uint32_t v1 = (int32_t)a2; // 0x1375
    uint32_t v2 = v1 % 32; // 0x1375
    uint32_t v3 = (8 - v1) % 32; // 0x1389
    int32_t v4 = 0; // 0x13a2
    char * v5 = (char *)((int64_t)v4 + (int64_t)str); // 0x1366
    unsigned char v6 = *v5; // 0x1366
    uint32_t v7 = (int32_t)v6;
    char v8 = v3 == 0 ? v6 : (char)(v7 >> v3);
    *v5 = (v2 == 0 ? v6 : (char)(v7 << v2)) | v8;
    v4++;
    int32_t len = strlen((char *)str); // 0x13b3
    while (v4 < len) {
        // 0x1359
        v5 = (char *)((int64_t)v4 + (int64_t)str);
        v6 = *v5;
        v7 = (int32_t)v6;
        v8 = v3 == 0 ? v6 : (char)(v7 >> v3);
        *v5 = (v2 == 0 ? v6 : (char)(v7 << v2)) | v8;
        v4++;
        len = strlen((char *)str);
    }
    // 0x13bd
    return len;
}

// Address range: 0x13c5 - 0x144d
// Demangled:     long double
int64_t e(int64_t * str) {
    int64_t v1 = (int64_t)str;
    int64_t v2 = 0; // 0x1443
    if (strlen((char *)str) == 1) {
        // 0x1445
        return 0;
    }
    int32_t v3 = 0; // 0x1443
    char * v4 = (char *)(v2 + v1); // 0x13e8
    *v4 = *(char *)((v2 | 1) + v1);
    *(char *)((int64_t)(v3 | 1) + v1) = *v4;
    v3 += 2;
    v2 = v3;
    int64_t result = (int64_t)strlen((char *)str) - 1; // 0x143c
    while (result > v2) {
        // 0x13db
        v4 = (char *)(v2 + v1);
        *v4 = *(char *)((v2 | 1) + v1);
        *(char *)((int64_t)(v3 | 1) + v1) = *v4;
        v3 += 2;
        v2 = v3;
        result = (int64_t)strlen((char *)str) - 1;
    }
    // 0x1445
    return result;
}

// Address range: 0x144d - 0x14b3
// Demangled:     float
int64_t f(int64_t * str) {
    uint32_t len = strlen((char *)str); // 0x1460
    if (len <= 0) {
        // 0x14a6
        return putchar(10);
    }
    int64_t v1 = 0;
    printf("%02x", (int32_t)*(char *)(v1 + (int64_t)str));
    v1++;
    while (v1 != (int64_t)len) {
        // 0x1471
        printf("%02x", (int32_t)*(char *)(v1 + (int64_t)str));
        v1++;
    }
    // 0x14a6
    return putchar(10);
}

// Address range: 0x14b4 - 0x14bd
int64_t _fini(void) {
    // 0x14b4
    int64_t result; // 0x14b4
    return result;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (13.3.0)
// Detected functions: 18

